# config.yaml

main:
  components_repository: "https://github.com/SaraLuzVC/Case-Study-House-Prices-"
  project_name: Case Study (House Prices)
  steps: all
etl:
  train_data: "train.csv"
  test_data: "test.csv"
  min_price: 199,628,000.00  # pesos OJO no tienen mucho sentido porque no son del mercado mexicano actual
  max_price: 4,318,600,000.00  # pesos OJO no tienen mucho sentido porque no son del mercado mexicano actual
modeling:
  # Fraction of data to use for test (the remaining will be used for train and validation)
  test_size: 0.33
  # Fix this for reproducibility, change to have new splits
  random_seed: 42 # 42 is the answer to everything
  # RandomForestRegressor. This is a subsample, but more could be added:
  random_forest:
    default: &DEFAULTRF
      n_estimators: 100
      criterion: "squared_error"
      max_depth: None
      min_samples_split: 2
      min_samples_leaf: 1
      min_weight_fraction_leaf: 0.0
      max_features: 1.0
      max_leaf_nodes: None
      min_impurity_decrease: 0.0
      bootstrap: true
      oob_score: false
      n_jobs: None
      random_state: None
      verbose: 0
      warm_start: false
      ccp_alpha: 0.0
      max_samples: None
      monotonic_cst: None
    model:
      <<: *DEFAULTRF
      min_samples_split: 3
      random_state: 5
  knn:
    default: &DEFAULTKNN
      n_neighbors: 5
      weights: "uniform"
      algorithm: "auto"
      leaf_size: 30
      p: 2
      metric: "minkowski"
      metric_params: null
      n_jobs: null
    model:
      <<: *DEFAULTKNN
      algorithm: "ball_tree"
      n_neighbors: 7
      weights: "distance"
      

